### ISSUE TITLE
The Google Maps row breaks the UX when scrolling on the page 

### ISSUE THREAD

**Issue by conorgil** [microservicesday/website#16]
I'm not sure whether this is hugely important, but I didn't know where else to leave feedback. The Google Maps area of the website spans the entire web page. When I am scrolling (both on mobile and on desktop) I encounter the Google Maps area and then my finger/mouse starts interacting with the map by zooming in/out. I did not expect this and found it difficult to scroll down the page to the content below the map (especially on mobile).

Anyways, I hope this feedback is useful. Sorry I don't have time for a PR fix.

**Comment by Joe8Bit** [comment]
Thanks for this @conorgil we're in the process of fixing this at the moment!

**Comment by Joe8Bit** [comment]
@conorgil this should now be fixed and deployed, could you validate it's fixed?

**Comment by conorgil** [comment]
Fix confirmed
