### ISSUE TITLE
Create domain alias for conf wall

### ISSUE THREAD

**Issue by Joe8Bit** [microservicesday/website#20]
We need to create the `http://wall.microservicesday.com` sub-domain. It'll just be a domain alias onto this:

`http://microservices-day.confwall.com/`

**Comment by Joe8Bit** [comment]
Is this something that you can take care of @MikeZTaylor?

**Comment by MikeZTaylor** [comment]
I can look into it, I would need to know what service are you using to host the site with.

**Comment by MikeZTaylor** [comment]
Hi @Joe8Bit, I've tried to get it working and nothing yet, the redirect doesn't seem to be working. Would it be better to perhaps add a link to the website for the subdomain? We've contacted confwall to see if they can shed some light on the issue and just waiting on a reply. CC @ckiss

**Comment by MikeZTaylor** [comment]
Hi @Joe8Bit , we got a response back from conferral basically it boils down to that on the free tier the functionality of aliasing like we had planned is not a feature and we would have to upgrade to a paid wall for this functionality. CC @ckiss

**Comment by Joe8Bit** [comment]
Thanks @MikeZTaylor appreciate the assistance, will close this, the raw domain will have to do!
