### ISSUE TITLE
Repo access rights

### ISSUE THREAD

**Issue by matt-oc** [microservicesday/website#25]
@Joe8Bit Hi Joe, sorry for all the hassle. I understand you have sent invites but we haven't received anything. If you get a chance i'd appreciate it if you could resend.
thanks for your help.

**Comment by Joe8Bit** [comment]
Should be dealt with, both Cian and yourself now have invites. It seems there is a user called matt-co that got invited (and now that invite rescinded!).

**Comment by matt-oc** [comment]
Thanks for your help, invite received.
